services:
  keycloak:
    build:
      context: .
      dockerfile: ./docker/keycloak/Dockerfile
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: $KC_DB_PASSWORD
      KC_DB_URL_DATABASE: $KC_DB_URL_DATABASE
      KC_DB_URL: jdbc:postgresql://postgres:5432/$KC_DB_URL_DATABASE
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: $KC_DB_USERNAME
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_HOSTNAME: $KC_HOSTNAME
      KC_PROXY: edge
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - keycloak
    depends_on:
      - postgres
    mem_limit: 1g
    cpus: "1.0"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: $KC_DB_URL_DATABASE
      POSTGRES_PASSWORD: $KC_DB_PASSWORD
      POSTGRES_USER: $KC_DB_USERNAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak
    mem_limit: 1g
    cpus: "1.0"

volumes:
  keycloak_data:
  postgres_data:

networks:
  keycloak:
    driver: bridge
